version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: pedidos-service/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  

